@@ -17,10 +17,10 @@
#     artifact-name: corne_left_with_logging
#
include:
  - board: adafruit_kb2040
    shield: ninepad
  - board: sparkfun_pro_micro_rp2040
    shield: ninepad
  # - board: adafruit_kb2040
  #   shield: ninepad
  # - board: sparkfun_pro_micro_rp2040
  #   shield: ninepad
  - board: nice_nano
    shield: ninepad
  - board: nice_nano_v2
